### ISSUE TITLE
October saws only 30th days

### ISSUE THREAD

**Issue by Willi-Dev-E-Loper** [ddmy/vue-gantt#27] opened 2023-11-29 12:00 UTC
Im improving this component to adjust it to my requeriments and i watched a little and easy correction bug.
In Utils/index.js -> this function need to set the hour becouse the diference in hours makes missed last day on october

```
export const fethDaysRange = (start, stop) => {
  let current = new Date(start.replace(/\//g, '-'))
  const end = new Date(stop)
  current.setHours(0, 0, 0, 0); // Establecer las horas a las 00:00:00

  const result = [];

  while (end.getTime() >= current.getTime()) {
    const res = fetchDayDetail(current);
    result.push(`${res.year}-${res.month}-${res.day}`);
    current.setDate(current.getDate() + 1);
  }

  return result;
}
```

**Comment by ddmy** [comment] 2023-12-05 03:05
Thank you very much for your support and suggestions. I am very surprised and happy.🙏

Can you explain in detail how you called this method? For example, the parameters passed?

```
fethDaysRange('2023-10-1', '2023-11-1')
fethDaysRange('2023-9-18', '2023-11-1')
```

I followed the above example and returned the correct results.

Of course, if you can identify the problem and raise a PR, it must be great!💗

**Comment by ddmy** [comment] 2023-12-07 02:33
Yes, the problem you mentioned does exist, and I have fixed it now. #28 

I want to apologize because I didn't read this issue carefully at the beginning, which led me to mistakenly believe that it was not a problem. When I confirmed again today, I found out that it was my own personal mistake. I apologize. I have now fixed and updated the version.

**Closed as completed by ddmy** 2023-12-07 02:33 UTC
